Iter9
vysogota0399/mem_stats_monitoring pull request #9
Opened 2024-12-24 22:46 UTC by vysogota0399

2024-12-26 08:22 UTC, zhark0vv requested changes

2024-12-26 08:22 UTC, zhark0vv commented on agent
Добавь бинари в gitignore, пожалуйста.

2024-12-26 08:22 UTC, zhark0vv commented on internal/server/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Тты используешь Singleton, у тебя есть один глобальный логгер.
Но в Go это антипаттерн. И причин этому две:

- существование концепции поинтеров
- duck-typing

В Go очень хорошо реализуется классический DI, а отсутствие новых объектов гарантируется поинтерами.
Здесь стоит сделать просто обертку, ее конструктор, создать объект логгера в main-пакете и инжетировать ее туда, где она нужна.

2024-12-26 08:22 UTC, zhark0vv commented on internal/server/models/gauge_test.go
> +func TestMarshaler(t *testing.T) {
В пакете JSON уже есть свои тесты, обычно такое не тестируют.

2024-12-26 08:22 UTC, zhark0vv commented on internal/server/storage/persistence.go
> +func newDataReader(ctx context.Context, filename string, strg Storage) (*DataReader, error) {
Концептуально в Go, лучше не принимать имя файла на вход, а вместо этого использовать дескрипторы из io.
Например, `io.Writer`, тогда твоему коду будет безразлично, куда ты пишешь результат.

Пусть решение о том, куда писать примет потребитель, а не `Storage`.

2024-12-26 08:22 UTC, zhark0vv commented on internal/server/storage/persistence.go
> +func (m *PersistentMemory) Dump() error {
Можно перейти из pull-модели (читаем весь репозиторий и кладем всю пачку рез в х минут) на пуш-модель. Пуш-модель - это когда сервисный слой создаст в очереди событие о том, что метрика создана, а читатель обработает и положит в файл.

Можно сделать на каналах.

2024-12-26 08:22 UTC, zhark0vv commented on internal/server/storage/storage.go
> +	restore() error
Интерейсы не должны содержать приватные методы.

2024-12-26 08:22 UTC, zhark0vv commented on server
Еще один бинарь, стоит убрать.

2024-12-26 08:22 UTC, zhark0vv commented on cmd/server/main.go
> +		log.Fatal(err)
На этом уровне у тебя уже есть zap, стоит использовать его.

2024-12-26 08:22 UTC, zhark0vv commented on cmd/server/main.go
> +		log.Fatal(err)
И тут тоже zap уже есть.

2024-12-26 09:07 UTC, vysogota0399 commented on internal/server/models/gauge_test.go
> +func TestMarshaler(t *testing.T) {
я уберу,
У меня не было цели проверять работы пакета json))
Просто дебажил ТК на котором падал ci в гитхабе

2025-01-04 14:08 UTC, vysogota0399 commented on agent
дселал

2025-01-04 14:10 UTC, vysogota0399 commented on internal/server/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
сделал

2025-01-04 14:10 UTC, vysogota0399 commented on server
убарл

2025-01-05 20:09 UTC, vysogota0399 commented on internal/server/storage/persistence.go
> +func (m *PersistentMemory) Dump() error {
сделал

2025-01-07 14:56 UTC, zhark0vv approved these changes

2025-01-07 14:56 UTC, zhark0vv commented on internal/server/storage/pubsub/pubsub_test.go
> +// func TestSubscriber_Start(t *testing.T) {
Лишний код, стоит убрать.

2025-01-07 14:56 UTC, zhark0vv commented on internal/utils/logging/logging.go
> +func NewZapLogger(level zapcore.Level) (*ZapLogger, error) {
Вижу, что ты используешь решение, которое мы вместе дотюнивали, спасибо. :)
----

Предложение: ты почти всегда игнорируешь ошибку. Можно сделать этот метод must-методом (MustZapLogger) и кидать панику. Так делают в случае, если вероятность ошибки нулевая.

2025-01-07 14:56 UTC, zhark0vv commented on internal/server/storage/pubsub/pubsub.go
> +	ftarget, ok := target.(*os.File)
Читеришь! :)

Такой каст не безопасен (с учетом, что ты проверил ok - не совсем), также ты не развязал логику, этот компонент по прежнему может работать только с файлом.

На этом уровне - это только Writer/Reader/Closer, файл лучше открыть на уровне выше.

2025-01-08 18:42 UTC, merged